import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import ClientInit from './components/ClientInit';

const getPoppins = Poppins({
  weight: '400',
  style: 'normal',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={getPoppins.className}>
        {' '}
        <ClientInit />
        <script src="https://js.puter.com/v2/"></script>
        {children}
      </body>
    </html>
  );
}
